export const siteConfig = {
  name: "Robot Cafe",
  phone: "0769 30 30 30",
  phoneIntl: "+254 769 303030",
  email: "info@robotcafe.co.ke",
  address: "Lana Plaza, Oloitoktok Rd, Nairobi",
  openingHours: "Mon - Sun, 7:30 AM - 10 PM",
  whatsappUrl: "https://wa.me/254769303030",
  branches: [
    {
      id: "lana-plaza",
      name: "Robot Cafe - Lana Plaza",
      shortName: "Lana Plaza",
      address: "Lana Plaza, Oloitoktok Rd, Nairobi",
      phone: "0769 30 30 30",
      phoneIntl: "+254 769 303030",
      reservationInbox: "reservation@robotcafe.co.ke",
      reservationRoutingLabel: "Lana Plaza reservation desk",
      diaryPlaceName: "Robot Cafe - Lana Plaza",
    },
    {
      id: "imaara-mall",
      name: "Robot Cafe - Imaara Mall",
      shortName: "Imaara Mall",
      address: "Ground Floor, Imaara Mall along Mombasa Road",
      phone: "0140 30 30 30",
      phoneIntl: "+254 140 303030",
      reservationInbox: "reservation@robotcafe.co.ke",
      reservationRoutingLabel: "Imaara Mall reservation desk",
      diaryPlaceName: "Robot Cafe - Imaara Mall",
    },
  ],
  navItems: [
    { label: "Offers", path: "/offers" },
    { label: "Our Menu", path: "/menu" },
    { label: "Reviews", path: "/reviews" },
    { label: "About Us", path: "/about-us" },
    { label: "FAQ", path: "/faq" },
    { label: "Contact Us", path: "/contact" },
  ],
};
